### ISSUE TITLE
cannot use keepassxc as secret service provider

### ISSUE THREAD

**Issue by soredake** [flathub/com.github.vladimiry.ElectronMail#1]
With electronmail from flatpak and keepassxc from ubuntu repos:
![image](https://user-images.githubusercontent.com/5204968/93717242-1cbf3c00-fb7d-11ea-85b1-9f7d1398f0f4.png)
![image](https://user-images.githubusercontent.com/5204968/93717247-247ee080-fb7d-11ea-85f4-79c97dd074a7.png)

With electronmail from appimage and keepassxc from ubuntu repos:
![image](https://user-images.githubusercontent.com/5204968/93717261-4f693480-fb7d-11ea-80ce-866e83802710.png)
![image](https://user-images.githubusercontent.com/5204968/93717263-5abc6000-fb7d-11ea-9e5b-f081c9e6a00d.png)

Kubuntu 20.04

**Comment by vladimiry** [comment]
See [here](https://github.com/flathub/flathub/pull/1656) the first point of "Known issues" paragraph.

**Comment by soredake** [comment]
Oops, keepassxc from ppa, version 2.6.1, sorry for my mistake

**Comment by vladimiry** [comment]
Just tried KeePassXC 2.6.1 + `flatpak install flathub com.github.vladimiry.ElectronMail` on Arch Linux system and it worked well for me. There is nothing I could do to make it work for you.

**Comment by soredake** [comment]
>upstream issue

KeePassXC or ElectronMail?

**Comment by vladimiry** [comment]
> KeePassXC or ElectronMail?

System / KeePassXC / https://github.com/atom/node-keytar. Since it works for me then it's likely the issue with your system or how KeePassXC handles things on your system.

**Comment by soredake** [comment]
Maybe related https://gitlab.gnome.org/GNOME/libsecret/-/issues/49

**Comment by vladimiry** [comment]
The `gcrypt` compilation option indeed exists as listed in https://github.com/GNOME/libsecret/blob/master/meson_options.txt. Going to try it.

**Comment by vladimiry** [comment]
The `beta` branch has been updated. Use `flatpak-builder --force-clean --repo=repo --user --install build-dir com.github.vladimiry.ElectronMail.json` to build and install the app.

**Comment by soredake** [comment]
@vladimiry thanks, it's finally working!

**Comment by vladimiry** [comment]
Will be merged to master branch then in along with the next release.

**Comment by vladimiry** [comment]
> Will need to test it on the system with gnome-keyring secret service implementation (so far tested with the keepasscx implementation only).

Works well on Ubuntu with gnome-keyring.
