### ISSUE TITLE
The app no longer starts when the "user namespace" feature is disabled on the system (v4.10.0 in beta branch)

### ISSUE THREAD

**Issue by vladimiry** [flathub/com.github.vladimiry.ElectronMail#3]
Here is the console output of `flatpak run com.github.vladimiry.ElectronMail` execution:

bwrap: No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl kernel.unprivileged_userns_clone=1'.
error: ldconfig failed, exit status 256

Steps to reproduce:
- `flatpak install --user https://dl.flathub.org/build-repo/33589/com.github.vladimiry.ElectronMail.flatpakref` (beta build of v4.10.0 triggered by https://github.com/flathub/com.github.vladimiry.ElectronMail/commit/e1a2ddd2665a799b92adc1930c6f270e31bc7b75)
- `sudo sysctl kernel.unprivileged_userns_clone=0` (making sure that "user namespace" thing is disabled on the system)
- `flatpak run com.github.vladimiry.ElectronMail`

Or you can also reproduce it by building package locally:
- `git clone https://github.com/flathub/com.github.vladimiry.ElectronMail.git`
- `git checkout beta`
- `flatpak-builder --force-clean --repo=repo --user --install build-dir com.github.vladimiry.ElectronMail.json`
- `sudo sysctl kernel.unprivileged_userns_clone=0` (making sure that "user namespace" thing is disabled on the system)
- `flatpak run com.github.vladimiry.ElectronMail`

I thought that `zypak-wrapper` tool is supposed to do the trick when the user namespace is disabled on the system. CC @refi64

When the previous/v4.9.2 app version was releasing I think there was no such issue. So the guess is that something has changed at the flatpak-evironment/zypak-wrapper side. CC @nedrichards

**Comment by vladimiry** [comment]
Also the same error gets printed to console when I just run `flatpak uninstall com.github.vladimiry.ElectronMail` but the removing actually completes.

**Comment by refi64** [comment]
Is bwrap setuid? It needs to be setuid if you doesn't have unprivileged user namespaces enabled...

**Comment by vladimiry** [comment]
`stat $(which bwrap)` cal shows `0755/-rwxr-xr-x` permissins. Can confirm that changing it to 4755 makes things work. Still wondering how it worked before.

**Comment by vladimiry** [comment]
Still interested in how to make the package work for everyone without a need to manually tweaking the systems. For non-container-like packages I normally set 4755 for chrome-sandbox binary https://github.com/vladimiry/ElectronMail/blob/67de6206ffaee48e2850876fdc33ae021b2ea64e/scripts/electron-builder/hooks/afterPack/index.ts#L24 and the add/embed the `--no-sandbox` arg for them. And for example fro pacman package it's also explicitly done https://aur.archlinux.org/cgit/aur.git/tree/electronmail-bin.install?h=electronmail-bin#n10
Maybe I should tweak the flatpak package build pipeline somehow so there is no need to, like adding `--no-sandbox` arg similar way it's done for appimage and snap packages?

**Comment by refi64** [comment]
Related, flatpak/flatpak#4035. For reference:

> Flatpak's own top-level, **mandatory** sandbox requires a functioning bwrap, which itself needs either unprivileged user namespaces or the setuid bit to work. Zypak works from *inside* this sandbox, i.e. at the point where this error happens, Zypak is not even running yet.

**Comment by vladimiry** [comment]
Thanks for the input. Closing this issue in favor of https://github.com/flatpak/flatpak/issues/4035.
